{% set name = "disCoverage" %}
{% set version = "0.6.0" %}
  
package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ..

requirements:
  build:
    - python=3.8.5
  run:
    - python=3.8.5
    - r-base=3.6.3
    - r-data.table =1.14.0
    - r-dplyr =1.0.6
    - r-readr =1.4.0
    - r-rmpfr =0.8_4
    - r-stringi =1.5.3
    - mosdepth=0.3.2
    - tabix
