{% set name = "disCoverage" %}
{% set version = "0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ..

requirements:
  host:
    - python =3.8.5
    - r-base
  run:
    - python =3.8.5
    - r-base >=3.6
    - r-data.table =1.14.0
    - r-dplyr =1.0.7
    - r-readr =2.0.1
    - r-rmpfr =0.8_4
    - r-stringi >=1.4.3

tests:
  commands:
    - mosdepth -h
    - disCoverage -h
