{% set name = "disCoverage" %}
{% set version = "0.6.6" %}
{% set py_version = "3.8.5" %}
{% set build = 2 %}
  
package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  number: {{ build }}

source:
  path: ..

requirements:
  build:
    - python={{ py_version }}
  run:
    - python={{ py_version }}
    - r-base=3.6.3
    - r-data.table =1.14.0
    - r-dplyr =1.0.6
    - r-readr =1.4.0
    - r-rmpfr =0.8_4
    - r-stringi =1.5.3
    - mosdepth=0.3.2
    - tabix =1.11

tests:
  imports:
    - preparePlottingCoverage
  commands:
    - disCoverage -h
    - disCoverage --version | grep -e {{ version }}

about:
  home: https://github.com/javiercguard/disCoverage/edit/main/conda/meta.yaml
