{% set name = "disCoverage" %}
{% set version = "0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ..

requirements:
  host:
    - python =3.8.5
    - r-base =3.6.3
  run:
    - python =3.8.5
    - r-base =3.6.3
    - r-data.table
    - r-dplyr
    - r-readr
    - r-rmpfr
    - r-stringi

tests:
  commands:
    - mosdepth -h
    - disCoverage -h
